name: "Setup Java + Maven cache"
description: "Sets up a JDK (Temurin by default) and enables Maven dependency caching"

inputs:
  java-version:
    description: "JDK version to install"
    required: false
    default: "25"
  distribution:
    description: "JDK distribution (e.g., temurin, zulu, corretto)"
    required: false
    default: "temurin"
  cache-dependency-path:
    description: "Path(s) used to compute Maven cache key (supports glob patterns)"
    required: false
    default: "**/pom.xml"

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        
    - name: Cache Maven dependencies
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles(inputs.cache-dependency-path) }}
        restore-keys: ${{ runner.os }}-m2
